import { type SupportTopic } from '../types'

// Guide för Annonser-sidan. En sektion per under-flik, i samma ordning som
// flikarna. Sektions-id matchar flikarnas id så att hjälpknappen kan
// djuplänka till rätt avsnitt.
export const annonser: SupportTopic = {
  id:    'annonser',
  title: { sv: 'Annonser', en: 'Ads' },
  intro: {
    sv: 'Annonser-sidan visar vad dina Google-annonser kostar och vad du får tillbaka. Den svarar på tre frågor: lönar sig annonserna, vilka sökord fungerar, och hur ser annonserna ut? Sidan pekar också ut var pengar läcker — och låter dig täppa till läckan direkt.',
    en: 'The Ads page shows what your Google ads cost and what you get back. It answers three questions: are the ads paying off, which keywords work, and what do the ads look like? The page also points out where money is leaking — and lets you plug the leak right away.',
  },
  sections: [
    {
      id: 'overview',
      heading: { sv: 'Översikt', en: 'Overview' },
      body: [
        {
          sv: 'Översikten är din månadskoll. Fyra kort visar de viktigaste siffrorna: vad du lagt, vad det gav och vad varje kund kostade. Under korten ser du budgeten och dina kampanjer.',
          en: 'The overview is your monthly check-in. Four cards show the key numbers: what you spent, what it brought in and what each customer cost. Below the cards you see the budget and your campaigns.',
        },
        {
          sv: 'Börja alltid med det gröna kortet — kunder eller bokningar från annonser. Det är hela poängen med att annonsera. Kostnaden i sig säger ingenting utan den siffran bredvid.',
          en: 'Always start with the green card — customers or bookings from ads. That is the whole point of advertising. The cost on its own says nothing without the number next to it.',
        },
        {
          sv: 'Ser du en röd rad om pengar som slösas? Klicka på den. Den tar dig till Sökord-fliken där du kan stoppa slöseriet med ett klick.',
          en: 'See a red row about money being wasted? Click it. It takes you to the Keywords tab where you can stop the waste with one click.',
        },
        {
          sv: 'Varje kampanjrad går att fälla ut. Där ser du kampanjens bästa sökord, dess sämsta och en snabb summering — utan att lämna översikten.',
          en: "Every campaign row can be expanded. There you see the campaign's best keyword, its worst and a quick summary — without leaving the overview.",
        },
      ],
      terms: [
        { term: { sv: 'Total kostnad', en: 'Total cost' },
          def:  { sv: 'Så mycket du har lagt på annonser hittills denna månad. Siffran är bara bra eller dålig i förhållande till hur många kunder den gav.',
                  en: 'How much you have spent on ads so far this month. The number is only good or bad in relation to how many customers it brought.' } },
        { term: { sv: 'Kunder från annonser', en: 'Customers from ads' },
          def:  { sv: 'Personer som klickade på en annons och sedan ringde, skickade ett formulär eller köpte något. Det gröna kortet — sidans viktigaste siffra.',
                  en: 'People who clicked an ad and then called, sent a form or bought something. The green card — the most important number on the page.' } },
        { term: { sv: 'Bokningar från annonser', en: 'Bookings from ads' },
          def:  { sv: 'Har du bokningssystemet visas bokningar i stället, med det totala bokningsvärdet i kronor under.',
                  en: 'If you have the booking system, bookings are shown instead, with the total booking value in kronor underneath.' } },
        { term: { sv: 'Kostnad per kund / per bokning', en: 'Cost per customer / per booking' },
          def:  { sv: 'Vad du i snitt betalade i annonser för varje kund. Jämför med vad en kund är värd för dig — ligger kostnaden under värdet tjänar du pengar på annonserna.',
                  en: 'What you paid in ads, on average, for each customer. Compare it with what a customer is worth to you — if the cost is below the value, the ads are making you money.' } },
        { term: { sv: 'Personer som klickade', en: 'People who clicked' },
          def:  { sv: 'Antal klick på dina annonser denna månad. Många klick men få kunder betyder att något efter klicket brister — ofta sidan folk landar på.',
                  en: 'The number of clicks on your ads this month. Many clicks but few customers means something after the click is failing — often the page people land on.' } },
        { term: { sv: 'Varje krona kom tillbaka som X kr', en: 'Every krona came back as X kr' },
          def:  { sv: 'Den gröna rubriken jämför annonskostnaden med bokningsvärdet. Över 1 kr betyder att annonserna ger tillbaka mer än de kostar. Ju högre, desto bättre.',
                  en: 'The green headline compares the ad cost with the booking value. Above 1 kr means the ads bring back more than they cost. The higher, the better.' } },
        { term: { sv: 'Pilarna under korten', en: 'The arrows under the cards' },
          def:  { sv: 'Jämför med förra perioden. Grön pil är en förbättring, röd en försämring. En enskild period kan svänga — titta på riktningen över tid innan du ändrar något.',
                  en: 'Compare with the previous period. A green arrow is an improvement, a red one a decline. A single period can swing — look at the direction over time before changing anything.' } },
        { term: { sv: 'Röda raden om slösade pengar', en: 'The red row about wasted money' },
          def:  { sv: 'Summan du lagt på sökningar och sökord som aldrig blir kunder. Klicka på knappen så kommer du till listan där du kan blockera dem.',
                  en: 'The amount you have spent on searches and keywords that never become customers. Click the button to go to the list where you can block them.' } },
        { term: { sv: 'Månadsbudget', en: 'Monthly budget' },
          def:  { sv: 'Stapeln visar hur mycket av månadens budget som är använd. Det vita strecket visar var i månaden du är. Ligger stapeln långt före strecket går pengarna för fort.',
                  en: "The bar shows how much of the month's budget has been used. The white line shows where in the month you are. If the bar is well ahead of the line, the money is going too fast." } },
        { term: { sv: 'Beräknat vid månadens slut', en: 'Projected at end of month' },
          def:  { sv: 'En prognos byggd på din takt hittills. "I fas" betyder att budgeten räcker månaden ut. En varning betyder att budgeten tar slut i förtid — då slutar annonserna visas de sista dagarna.',
                  en: 'A forecast based on your pace so far. "On track" means the budget will last the month. A warning means the budget runs out early — then the ads stop showing for the final days.' } },
        { term: { sv: 'Månadskostnad', en: 'Monthly cost' },
          def:  { sv: 'Staplarna visar vad annonserna kostat de senaste månaderna. Den gula stapeln är nuvarande månad. Använd den för att se om kostnaden smyger uppåt.',
                  en: 'The bars show what the ads have cost in recent months. The yellow bar is the current month. Use it to see if the cost is creeping upwards.' } },
        { term: { sv: 'Aktiv / Pausad', en: 'Live / Paused' },
          def:  { sv: 'Kampanjens läge. Klicka på knappen för att pausa eller starta kampanjen. En pausad kampanj kostar ingenting men syns inte heller.',
                  en: "The campaign's status. Click the button to pause or start the campaign. A paused campaign costs nothing but is not shown either." } },
        { term: { sv: 'Dagsbudgeten', en: 'The daily budget' },
          def:  { sv: 'Det mesta kampanjen får kosta per dag. Klicka på beloppet för att ändra det direkt. Höj bara budgeten för kampanjer som redan ger kunder till bra pris.',
                  en: 'The most the campaign is allowed to cost per day. Click the amount to change it directly. Only raise the budget for campaigns that already bring customers at a good price.' } },
        { term: { sv: 'Spenderat denna månad', en: 'Spent this month' },
          def:  { sv: 'Kampanjens kostnad hittills denna månad. Jämför alltid med kundkolumnen bredvid.',
                  en: "The campaign's cost so far this month. Always compare it with the customer column next to it." } },
        { term: { sv: 'Kunder och per kund', en: 'Customers and per customer' },
          def:  { sv: 'Hur många kunder kampanjen gett och vad varje kund kostade. "Inga kunder ännu" på en kampanj som kostat mycket är en varningssignal — fäll ut raden och se varför.',
                  en: 'How many customers the campaign brought and what each one cost. "No customers yet" on a campaign that has cost a lot is a warning sign — expand the row and see why.' } },
        { term: { sv: 'Klick, Visningar, Snittkostnad per klick, Sökord', en: 'Clicks, Impressions, Average cost per click, Keywords' },
          def:  { sv: 'Kampanjens summering när du fäller ut raden: antal klick, hur många gånger annonserna visats, snittpriset per klick och hur många sökord kampanjen bjuder på.',
                  en: "The campaign's summary when you expand the row: the number of clicks, how many times the ads were shown, the average price per click and how many keywords the campaign bids on." } },
        { term: { sv: 'Bästa sökord', en: 'Best keyword' },
          def:  { sv: 'Sökordet som gett kampanjen flest kunder. Det ska få behålla eller öka sin budget.',
                  en: 'The keyword that has brought the campaign the most customers. It should keep or grow its budget.' } },
        { term: { sv: 'Slösar pengar', en: 'Wasting money' },
          def:  { sv: 'Kampanjens dyraste sökord utan en enda kund. Gå till Sökord-fliken och överväg att pausa det — pengarna gör mer nytta hos sökorden som fungerar.',
                  en: "The campaign's most expensive keyword without a single customer. Go to the Keywords tab and consider pausing it — the money does more good on the keywords that work." } },
      ],
    },
    {
      id: 'keywords',
      heading: { sv: 'Sökord', en: 'Keywords' },
      body: [
        {
          sv: 'Sökord är orden du betalar för att synas på. Den här fliken visar vilka som ger kunder och vilka som bara kostar. Det är här du sparar mest pengar.',
          en: 'Keywords are the words you pay to show up for. This tab shows which ones bring customers and which ones just cost money. This is where you save the most.',
        },
        {
          sv: 'Överst ligger sökningar som kostat pengar utan att ge en enda kund. Blockera dem — då visas dina annonser inte längre för de sökningarna, och budgeten flyttas automatiskt till sökningar som fungerar.',
          en: 'At the top are searches that have cost money without bringing a single customer. Block them — your ads then stop showing for those searches, and the budget automatically moves to searches that work.',
        },
        {
          sv: 'I listan under ser du varje sökord du bjuder på. Grön prick betyder att det ger kunder. Röd betyder att det kostar utan resultat. Grå betyder att det fortfarande testas. Klicka på en rad för hela bilden.',
          en: 'In the list below you see every keyword you bid on. A green dot means it brings customers. Red means it costs without results. Grey means it is still being tested. Click a row for the full picture.',
        },
        {
          sv: 'Pausa inte för snabbt. Ett sökord med få klick har inte hunnit visa vad det går för. Vänta tills det samlat runt tjugo klick innan du dömer det.',
          en: 'Do not pause too quickly. A keyword with few clicks has not had the chance to show what it can do. Wait until it has collected around twenty clicks before judging it.',
        },
      ],
      terms: [
        { term: { sv: 'Sökningar som kostar pengar utan att ge kunder', en: 'Searches that cost money without bringing customers' },
          def:  { sv: 'Exakta fraser folk sökt på där dina annonser visats och klickats — utan att någon blev kund. Summan överst är vad de kostat dig denna månad.',
                  en: 'Exact phrases people searched for where your ads were shown and clicked — without anyone becoming a customer. The amount at the top is what they have cost you this month.' } },
        { term: { sv: 'Blockera sökningen', en: 'Block this search' },
          def:  { sv: 'Stoppar dina annonser från att visas för just den sökningen. Pengarna går i stället till sökningar som ger kunder. Blockera allt som uppenbart inte är dina kunder, till exempel gratissökningar eller fel ort.',
                  en: 'Stops your ads from showing for that exact search. The money goes to searches that bring customers instead. Block everything that clearly is not your customers, such as searches for free services or the wrong town.' } },
        { term: { sv: 'Redan blockerade', en: 'Already blocked' },
          def:  { sv: 'Sökningar du blockerat tidigare. De kostar dig ingenting längre. Listan är hopfälld längst ner.',
                  en: 'Searches you have blocked before. They no longer cost you anything. The list is collapsed at the bottom.' } },
        { term: { sv: 'Aktiva / Pausade', en: 'Active / Paused' },
          def:  { sv: 'Filtret överst i listan. Aktiva sökord bjuder på visningar just nu. Pausade ligger kvar i kontot men kostar ingenting.',
                  en: 'The filter at the top of the list. Active keywords are bidding for impressions right now. Paused ones stay in the account but cost nothing.' } },
        { term: { sv: 'Etiketten efter sökordet', en: 'The label after the keyword' },
          def:  { sv: 'Matchningstypen — hur brett sökordet fångar sökningar. Exakt visar bara vid nästan identiska sökningar, fras och bred fångar fler varianter men också fler irrelevanta.',
                  en: 'The match type — how broadly the keyword catches searches. Exact shows only for nearly identical searches; phrase and broad catch more variants but also more irrelevant ones.' } },
        { term: { sv: 'Annonskostnad', en: 'Ad cost' },
          def:  { sv: 'Vad sökordet kostat denna månad, med antal klick under. Listan sorteras på kostnad — de dyraste ligger överst och förtjänar din uppmärksamhet först.',
                  en: 'What the keyword has cost this month, with the number of clicks underneath. The list is sorted by cost — the most expensive sit at the top and deserve your attention first.' } },
        { term: { sv: 'Resultat', en: 'Results' },
          def:  { sv: 'Grönt med antal kunder och pris per kund betyder att sökordet fungerar. "Testas" betyder för lite data än. "Inga resultat" betyder kostnad utan en enda kund — kandidat för paus.',
                  en: 'Green with a customer count and price per customer means the keyword works. "Testing" means too little data yet. "No results" means cost without a single customer — a candidate for pausing.' } },
        { term: { sv: 'Testas', en: 'Testing' },
          def:  { sv: 'Sökordet har färre än tjugo klick. Det är för lite för att dra slutsatser. Låt det rulla — ändra ingenting ännu.',
                  en: 'The keyword has fewer than twenty clicks. That is too little to draw conclusions. Let it run — change nothing yet.' } },
        { term: { sv: 'Visningar', en: 'Impressions' },
          def:  { sv: 'Hur många gånger annonsen visades för sökordet. Många visningar men få klick tyder på att annonstexten inte lockar.',
                  en: 'How many times the ad was shown for the keyword. Many impressions but few clicks suggests the ad copy is not tempting.' } },
        { term: { sv: 'Klickfrekvens', en: 'Click-through rate' },
          def:  { sv: 'Andelen som klickade av alla som såg annonsen. Under ett par procent är svagt — annonstexten matchar troligen inte det folk söker efter.',
                  en: 'The share of people who clicked out of everyone who saw the ad. Below a couple of percent is weak — the ad copy probably does not match what people are searching for.' } },
        { term: { sv: 'Snittkostnad per klick', en: 'Average cost per click' },
          def:  { sv: 'Vad du i snitt betalade varje gång någon klickade. Ett högt kvalitetsbetyg från Google pressar ner priset.',
                  en: 'What you paid on average each time someone clicked. A high quality score from Google pushes the price down.' } },
        { term: { sv: 'Konverteringsgrad', en: 'Conversion rate' },
          def:  { sv: 'Andelen klick som blev kunder. Runt fem procent är starkt för ett sökord. Lägre betyder att sidan folk landar på kan förbättras.',
                  en: 'The share of clicks that became customers. Around five percent is strong for a keyword. Lower means the page people land on can be improved.' } },
        { term: { sv: 'Kvalitetspoäng', en: 'Quality score' },
          def:  { sv: 'Googles betyg på sökordet, 1 till 10. Högt betyg ger billigare klick och bättre placering. Lågt betyg gör varje klick dyrare. Betyget byggs av tre delar som visas under.',
                  en: "Google's rating of the keyword, 1 to 10. A high score gives cheaper clicks and better placement. A low score makes every click more expensive. The score is built from three parts shown underneath." } },
        { term: { sv: 'Kommer folk klicka på din annons?', en: 'Will people click your ad?' },
          def:  { sv: 'Googles bedömning av hur ofta folk klickar på din annons jämfört med konkurrenternas för samma sökning. Rött här: gör annonstexten mer lockande.',
                  en: "Google's estimate of how often people click your ad compared with competitors' ads for the same search. Red here: make the ad copy more tempting." } },
        { term: { sv: 'Matchar din annons sökningen?', en: 'Does your ad match the search?' },
          def:  { sv: 'Hur väl annonstexten matchar det folk skrev in. Rött här: använd sökordets egna ord i rubrikerna.',
                  en: "How well the ad copy matches what people typed in. Red here: use the keyword's own words in the headlines." } },
        { term: { sv: 'Är din landningssida relevant?', en: 'Is your landing page relevant?' },
          def:  { sv: 'Hur användbar Google tycker att sidan efter klicket är. Rött här: se till att sidan handlar om exakt det sökordet lovar.',
                  en: 'How useful Google thinks the page after the click is. Red here: make sure the page is about exactly what the keyword promises.' } },
        { term: { sv: 'Sökord du inte bjuder på', en: 'Keywords you are not bidding on' },
          def:  { sv: 'Sökningar med hög köpvilja kopplade till dina tjänster som saknas i ditt konto. Siffrorna visar hur ofta de söks och ungefärligt klickpris. Lägg till de som matchar tjänster du faktiskt erbjuder.',
                  en: 'High-intent searches related to your services that are missing from your account. The numbers show how often they are searched and a rough click price. Add the ones that match services you actually offer.' } },
      ],
    },
    {
      id: 'ads',
      heading: { sv: 'Annonser', en: 'Ads' },
      body: [
        {
          sv: 'Den här fliken visar själva annonserna — texterna folk ser på Google. En annons består av flera rubriker och beskrivningar som Google kombinerar och testar automatiskt.',
          en: 'This tab shows the ads themselves — the texts people see on Google. An ad is made up of several headlines and descriptions that Google combines and tests automatically.',
        },
        {
          sv: 'Varje textrad har ett eget betyg. Google visar de bästa raderna oftare och undviker de svaga. Byt ut rader med betyget Låg — de drar ner hela annonsen. Rader som testas låter du vara ett par veckor.',
          en: 'Every text line has its own rating. Google shows the best lines more often and avoids the weak ones. Replace lines rated Low — they drag down the whole ad. Leave lines that are still being tested alone for a couple of weeks.',
        },
        {
          sv: 'Du kan ändra texterna direkt härifrån. Klicka på Ändra texten, skriv om och spara. Ändringarna skickas till Google och börjar gälla efter deras granskning.',
          en: 'You can edit the texts right here. Click Edit the text, rewrite and save. The changes are sent to Google and take effect after their review.',
        },
        {
          sv: 'Längst ner ser du annonstilläggen — extra rader som telefonnummer, länkar och fördelar. De kostar ingenting och gör annonsen större på skärmen. Sätt upp allt som saknas.',
          en: 'At the bottom you see the ad extensions — extra lines like your phone number, links and selling points. They cost nothing and make the ad bigger on screen. Set up everything that is missing.',
        },
      ],
      terms: [
        { term: { sv: 'Styrkemärket (Utmärkt, Bra, Medel, Svag)', en: 'The strength badge (Excellent, Good, Average, Poor)' },
          def:  { sv: 'Googles helhetsbetyg på annonsen. Utmärkt visas oftare till lägre kostnad. Medel eller Svag: lägg till fler olika rubriker och använd dina sökords egna ord.',
                  en: "Google's overall rating of the ad. Excellent gets shown more often at a lower cost. Average or Poor: add more varied headlines and use your keywords' own words." } },
        { term: { sv: 'Bäst / Bra / Låg / Testas på textraderna', en: 'Best / Good / Low / Learning on the text lines' },
          def:  { sv: 'Betyget per rubrik och beskrivning. Bäst ger flest klick — behåll den. Låg undviks av Google — skriv om den. Testas betyder att Google fortfarande provar raden — vänta.',
                  en: 'The rating per headline and description. Best drives the most clicks — keep it. Low is avoided by Google — rewrite it. Learning means Google is still testing the line — wait.' } },
        { term: { sv: 'Visningar', en: 'Impressions' },
          def:  { sv: 'Hur många gånger annonsen visats på Google denna månad.',
                  en: 'How many times the ad has been shown on Google this month.' } },
        { term: { sv: 'Klickfrekvens', en: 'Click-through rate' },
          def:  { sv: 'Andelen som klickade av alla som såg annonsen. Låg klickfrekvens med många visningar betyder att texten inte lockar — se över rubrikerna.',
                  en: 'The share of people who clicked out of everyone who saw the ad. A low rate with many impressions means the text is not tempting — review the headlines.' } },
        { term: { sv: 'Klick och Kunder', en: 'Clicks and Customers' },
          def:  { sv: 'Antal klick på annonsen och hur många av dem som blev kunder. Klick utan kunder pekar på att sidan efter klicket behöver ses över.',
                  en: 'The number of clicks on the ad and how many of them became customers. Clicks without customers point to the page after the click needing a review.' } },
        { term: { sv: 'Ändra texten', en: 'Edit the text' },
          def:  { sv: 'Öppnar annonsens rubriker och beskrivningar för redigering. Minst tre rubriker och två beskrivningar krävs. Spara skickar ändringen till Google.',
                  en: "Opens the ad's headlines and descriptions for editing. At least three headlines and two descriptions are required. Save sends the change to Google." } },
        { term: { sv: 'Annonstillägg', en: 'Ad extensions' },
          def:  { sv: 'Extra rader under annonsen: telefonnummer, extra länkar, fördelar, adress och tjänstelista. Varje tillägg gör annonsen större och lättare att klicka på — utan extra kostnad.',
                  en: 'Extra lines under the ad: phone number, extra links, selling points, address and a services list. Every extension makes the ad bigger and easier to click — at no extra cost.' } },
        { term: { sv: 'Saknas / Aktiv', en: 'Missing / Active' },
          def:  { sv: 'Aktiv betyder att tillägget visas med dina annonser. Saknas betyder att det inte är uppsatt än — klicka på Sätt upp och fyll i. Börja med telefonnumret och de extra länkarna.',
                  en: 'Active means the extension is showing with your ads. Missing means it is not set up yet — click Set up and fill it in. Start with the phone number and the extra links.' } },
        { term: { sv: 'Telefonnummer', en: 'Phone number' },
          def:  { sv: 'Visar ditt nummer i annonsen så att folk kan ringa direkt från sökresultatet, utan att först besöka hemsidan.',
                  en: 'Shows your number in the ad so people can call straight from the search result, without visiting the website first.' } },
        { term: { sv: 'Extra länkar', en: 'Extra links' },
          def:  { sv: 'Länkar till fler sidor på din webbplats, till exempel priser eller kontakt. Ger annonsen mer plats och fler vägar in.',
                  en: 'Links to more pages on your website, such as prices or contact. Gives the ad more space and more ways in.' } },
        { term: { sv: 'Extra fördelar', en: 'Extra selling points' },
          def:  { sv: 'Korta säljargument som visas under annonsen, till exempel gratis offert eller service samma dag. Välj det som skiljer dig från konkurrenterna.',
                  en: 'Short selling points shown under the ad, such as free quotes or same-day service. Pick what sets you apart from the competition.' } },
        { term: { sv: 'Adress', en: 'Address' },
          def:  { sv: 'Visar din adress och karta i annonsen. Hämtas automatiskt från din Google-företagsprofil när du aktiverar tillägget.',
                  en: 'Shows your address and a map in the ad. Pulled automatically from your Google Business Profile when you enable the extension.' } },
        { term: { sv: 'Tjänstelista', en: 'Services list' },
          def:  { sv: 'En rad som listar dina tjänster under en kategori, till exempel Tjänster: balayage, slingor, klippning. Kräver minst tre värden.',
                  en: 'A line listing your services under a category, for example Services: balayage, highlights, haircuts. Requires at least three values.' } },
      ],
    },
  ],
}
