import { type SupportTopic } from '../types'

// Guide for the Google profile dashboard. One section per under-tab, in the
// order the tabs appear. Section ids match the tab ids so the help button
// can deep-link straight to the right section.
export const googleProfil: SupportTopic = {
  id:    'google-profil',
  title: { sv: 'Din Google-profil', en: 'Your Google profile' },
  intro: {
    sv: 'Din Google-profil är rutan med ditt företag som visas på Google och på kartan. För ett lokalt företag är den ofta det första en ny kund ser. Den här sidan samlar allt som rör profilen: vad den ger dig, dina recensioner, inlägg, foton, konkurrenterna omkring dig och en checklista som visar vad som saknas.',
    en: 'Your Google profile is the box with your business that appears on Google and on the map. For a local business it is often the first thing a new customer sees. This page gathers everything about the profile: what it brings you, your reviews, posts, photos, the competitors around you, and a checklist that shows what is missing.',
  },
  sections: [
    {
      id: 'overview',
      heading: { sv: 'Översikt', en: 'Overview' },
      body: [
        {
          sv: 'Översikten svarar på en fråga: vad ger din Google-profil dig just nu? Högst upp ser du det som behöver din uppmärksamhet — till exempel recensioner som väntar på svar. Varje rad har en knapp som tar dig direkt till rätt flik. Är allt klart visas en grön bekräftelse i stället.',
          en: 'The overview answers one question: what is your Google profile doing for you right now? At the top you see what needs your attention — for example reviews waiting for a reply. Each row has a button that takes you straight to the right tab. If everything is done, a green confirmation shows instead.',
        },
        {
          sv: 'Korten i mitten visar vad kunder faktiskt gjorde via din profil den här månaden. Samtal, vägbeskrivningar och besök på hemsidan är riktiga kundhändelser, inte bara visningar. Det är den här raden som visar om profilen ger dig affärer.',
          en: 'The cards in the middle show what customers actually did through your profile this month. Calls, direction requests and website visits are real customer actions, not just views. This is the row that tells you whether the profile brings you business.',
        },
        {
          sv: 'Stapeldiagrammet längst ner visar hur många gånger din profil visades på Google. Staplarna är delade i två färger: grönt är personer som hittade dig på kartan, blått är personer som sökte på ditt namn. Växer den gröna delen vinner du nya kunder som inte kände till dig innan.',
          en: "The bar chart at the bottom shows how many times your profile appeared on Google. The bars are split into two colours: green is people who found you on the map, blue is people who searched for your name. If the green part grows, you are winning new customers who didn't know you before.",
        },
        {
          sv: 'Med väljaren uppe till höger byter du tidsperiod: veckovis, månadsvis eller årsvis. Titta på riktningen över flera perioder innan du drar slutsatser — en enskild vecka svänger alltid.',
          en: 'The picker at the top right switches the time period: weekly, monthly or yearly. Look at the direction over several periods before drawing conclusions — any single week always swings.',
        },
      ],
      terms: [
        { term: { sv: 'Behöver din uppmärksamhet', en: 'Needs your attention' },
          def:  { sv: 'Listan över sådant som väntar på dig just nu. En röd prick betyder bråttom, en gul betyder snart. Knappen på raden tar dig direkt till rätt flik.',
                  en: 'The list of things waiting for you right now. A red dot means urgent, a yellow one means soon. The button on the row takes you straight to the right tab.' } },
        { term: { sv: 'Bokade via din profil', en: 'Booked via your profile' },
          def:  { sv: 'Kunder som bokade efter att ha klickat på bokningslänken i din Google-profil. Summan i kronor räknas på dina faktiska bokningar. Visas bara om du har bokningssystemet.',
                  en: 'Customers who booked after clicking the booking link on your Google profile. The amount in kronor is based on your actual bookings. Only shown if you have the booking system.' } },
        { term: { sv: 'Personer ringde dig', en: 'People called you' },
          def:  { sv: 'Antal gånger någon tryckte på ring-knappen på din profil den här perioden. Varje samtal är en möjlig kund.',
                  en: 'How many times someone tapped the call button on your profile this period. Every call is a potential customer.' } },
        { term: { sv: 'Sökte vägbeskrivning', en: 'Asked for directions' },
          def:  { sv: 'Antal gånger någon bad Google om vägen till din adress. Ett starkt tecken på att personen tänker besöka dig.',
                  en: 'How many times someone asked Google for directions to your address. A strong sign that the person plans to visit you.' } },
        { term: { sv: 'Besökte din hemsida', en: 'Visited your website' },
          def:  { sv: 'Antal klick från din profil vidare till din hemsida. Personen ville veta mer innan den hörde av sig.',
                  en: 'The number of clicks from your profile through to your website. The person wanted to know more before getting in touch.' } },
        { term: { sv: 'Snittbetyg', en: 'Average rating' },
          def:  { sv: 'Ditt genomsnittliga stjärnbetyg från alla Google-recensioner, av högst 5. Det mest synliga förtroendetecknet på din profil — kunder jämför det med grannarnas.',
                  en: "Your average star rating across all Google reviews, out of 5. The most visible sign of trust on your profile — customers compare it with your neighbours'." } },
        { term: { sv: 'Procentpilen (↑ / ↓)', en: 'The percentage arrow (↑ / ↓)' },
          def:  { sv: 'Förändringen jämfört med förra perioden. Grön pil uppåt betyder att siffran växer, röd pil nedåt att den minskar.',
                  en: 'The change compared with the previous period. A green arrow up means the number is growing, a red arrow down means it is shrinking.' } },
        { term: { sv: 'Hittade dig på Maps', en: 'Found you on Maps' },
          def:  { sv: 'Den gröna delen av stapeln. Visningar från personer som sökte efter din typ av tjänst på kartan — utan att känna till ditt namn. Det är här nya kunder kommer ifrån.',
                  en: 'The green part of the bar. Views from people who searched for your type of service on the map — without knowing your name. This is where new customers come from.' } },
        { term: { sv: 'Sökte på ditt namn', en: 'Searched your name' },
          def:  { sv: 'Den blå delen av stapeln. Visningar från personer som skrev in ditt företagsnamn. De kände redan till dig, ofta via rekommendationer eller tidigare besök.',
                  en: 'The blue part of the bar. Views from people who typed in your business name. They already knew you, often through recommendations or earlier visits.' } },
        { term: { sv: 'Veckovis / Månadsvis / Årsvis', en: 'Weekly / Monthly / Yearly' },
          def:  { sv: 'Väljaren som styr vilken tidsperiod siffrorna och diagrammet visar. Månadsvis är bra vardagsläge; årsvis visar den långa trenden.',
                  en: 'The picker that controls which time period the numbers and the chart show. Monthly is a good everyday view; yearly shows the long-term trend.' } },
      ],
    },
    {
      id: 'reviews',
      heading: { sv: 'Recensioner', en: 'Reviews' },
      body: [
        {
          sv: 'Recensioner är den enskilt viktigaste faktorn för vem som visas först på kartan. Fliken visar ditt snittbetyg, hur betygen fördelar sig mellan en och fem stjärnor, och alla dina recensioner i en lista. Siffran på fliken visar hur många som väntar på svar.',
          en: 'Reviews are the single most important factor in who shows up first on the map. The tab shows your average rating, how the ratings are spread from one to five stars, and all your reviews in one list. The number on the tab shows how many are waiting for a reply.',
        },
        {
          sv: 'Rutan Få fler recensioner innehåller din personliga recensionslänk och färdiga meddelanden för sms och e-post. Kopiera och skicka till en nöjd kund direkt efter ett besök — de flesta hjälper gärna till när man frågar. Ett jämnt flöde av nya recensioner slår en stor engångsinsats.',
          en: 'The Get more reviews box holds your personal review link and ready-made messages for text and email. Copy and send one to a happy customer right after a visit — most people are glad to help when asked. A steady flow of new reviews beats one big push.',
        },
        {
          sv: 'Varje obesvarad recension har ett färdigt svarsförslag skrivet för just den recensionen. Läs igenom, gör det personligt och tryck Publicera svar — svaret hamnar direkt på Google. Svara på allt, även kritik. Nya kunder läser dina svar för att se hur du behandlar folk.',
          en: 'Every unanswered review comes with a suggested reply written for that specific review. Read it through, make it personal and press Publish reply — the reply goes straight onto Google. Reply to everything, including criticism. New customers read your replies to see how you treat people.',
        },
        {
          sv: 'En missnöjd kund är inte en katastrof. Svara lugnt, erkänn vad som gick fel och erbjud en lösning. Ett bra svar på en dålig recension bygger ofta mer förtroende än fem femstjärniga.',
          en: 'An unhappy customer is not a disaster. Reply calmly, acknowledge what went wrong and offer a solution. A good reply to a bad review often builds more trust than five five-star ones.',
        },
      ],
      terms: [
        { term: { sv: 'Snittbetyget och stjärnstaplarna', en: 'The average rating and the star bars' },
          def:  { sv: 'Den stora siffran är ditt genomsnitt av alla betyg. Staplarna bredvid visar hur många recensioner du fått per stjärnnivå, från fem ner till en.',
                  en: 'The big number is your average across all ratings. The bars next to it show how many reviews you have per star level, from five down to one.' } },
        { term: { sv: 'Svarsfrekvensen (procenttalet)', en: 'The response rate (the percentage)' },
          def:  { sv: 'Andelen av dina recensioner du har svarat på. Grönt är bra, gult okej, rött för lågt. Företag som svarar på det mesta upplevs som mer pålitliga.',
                  en: 'The share of your reviews you have replied to. Green is good, amber is okay, red is too low. Businesses that reply to most reviews come across as more trustworthy.' } },
        { term: { sv: 'Alla / Obesvarade', en: 'All / Unanswered' },
          def:  { sv: 'Filterknappar för listan. Obesvarade visar bara recensioner som väntar på svar — börja alltid där.',
                  en: 'Filter buttons for the list. Unanswered shows only reviews waiting for a reply — always start there.' } },
        { term: { sv: 'Besvarad', en: 'Replied' },
          def:  { sv: 'Den gröna etiketten som betyder att ditt svar redan är publicerat på Google. Recensionen behöver inget mer.',
                  en: 'The green label meaning your reply is already published on Google. The review needs nothing more.' } },
        { term: { sv: 'Föreslaget svar', en: 'Suggested response' },
          def:  { sv: 'En färdig svarstext anpassad efter recensionens innehåll och betyg. Ändra gärna något litet innan du publicerar — personligt slår mall.',
                  en: "A ready-made reply adapted to the review's content and rating. Change something small before you publish — personal beats template." } },
        { term: { sv: 'Publicera svar', en: 'Publish reply' },
          def:  { sv: 'Knappen som skickar ditt svar till Google. Svaret blir synligt för alla under recensionen på din profil.',
                  en: 'The button that sends your reply to Google. The reply becomes visible to everyone under the review on your profile.' } },
        { term: { sv: 'Tecken kvar', en: 'Characters remaining' },
          def:  { sv: 'Hur mycket plats du har kvar i svaret. Google sätter en maxgräns, men korta och varma svar fungerar bäst.',
                  en: 'How much room you have left in the reply. Google sets a maximum, but short, warm replies work best.' } },
        { term: { sv: 'Kopiera länk / Kopiera meddelande', en: 'Copy link / Copy message' },
          def:  { sv: 'Kopierar recensionslänken eller det färdiga meddelandet till urklipp. Klistra in i ett sms eller mejl till kunden.',
                  en: 'Copies the review link or the ready-made message to your clipboard. Paste it into a text or email to the customer.' } },
      ],
    },
    {
      id: 'posts',
      heading: { sv: 'Inlägg', en: 'Posts' },
      body: [
        {
          sv: 'Inlägg är korta nyheter som visas direkt på din Google-profil — erbjudanden, säsongstips eller att du har lediga tider. Regelbundna inlägg visar Google och kunderna att företaget lever. Ett inlägg i månaden räcker gott.',
          en: 'Posts are short updates shown directly on your Google profile — offers, seasonal tips or open appointment slots. Regular posts show Google and customers that the business is alive. One post a month is plenty.',
        },
        {
          sv: 'Veckans inläggsförslag är en färdigskriven text baserad på vad folk söker efter i din bransch just nu. Ändra det du vill, lägg till ditt telefonnummer eller din bokningslänk och tryck Publicera på Google. Du kan också lägga till en bild, en knapp eller schemalägga inlägget till ett senare datum.',
          en: "This week's post suggestion is a ready-written text based on what people in your industry are searching for right now. Change whatever you like, add your phone number or booking link and press Publish to Google. You can also add an image, a button, or schedule the post for a later date.",
        },
        {
          sv: 'Lägg alltid till ett foto om du kan. Inlägg med bild får betydligt mer uppmärksamhet än inlägg med bara text.',
          en: 'Always add a photo if you can. Posts with an image get far more attention than text-only posts.',
        },
        {
          sv: 'Under Senaste inläggen ser du vad du redan publicerat. Google tar bort inlägg automatiskt efter sex månader utan att säga till — färgen på varje rad visar hur lång tid inlägget har kvar.',
          en: 'Under Recent posts you see what you have already published. Google removes posts automatically after six months without telling you — the colour on each row shows how much time the post has left.',
        },
      ],
      terms: [
        { term: { sv: 'Veckans inläggsförslag', en: "This week's post suggestion" },
          def:  { sv: 'En färdig inläggstext byggd på vad folk söker efter i din bransch just nu. Du kan ändra allt innan du publicerar.',
                  en: 'A ready-made post text built on what people in your industry are searching for right now. You can change everything before publishing.' } },
        { term: { sv: 'Många söker just nu', en: 'Lots of searches right now' },
          def:  { sv: 'Den gröna etiketten som betyder att fler än vanligt söker efter din typ av tjänst den här månaden. Ett inlägg nu träffar extra många.',
                  en: 'The green label meaning more people than usual are searching for your type of service this month. A post published now reaches more people.' } },
        { term: { sv: 'Populära sökningar', en: 'Popular searches' },
          def:  { sv: 'Fraserna folk skriver in på Google just nu när de letar efter en tjänst som din. Väv gärna in dem naturligt i inläggstexten.',
                  en: 'The phrases people are typing into Google right now when looking for a service like yours. Weave them naturally into the post text.' } },
        { term: { sv: 'Tecken kvar', en: 'Characters remaining' },
          def:  { sv: 'Hur mycket plats du har kvar i inlägget. Räknaren blir gul och sedan röd när du närmar dig gränsen.',
                  en: 'How much room you have left in the post. The counter turns yellow and then red as you approach the limit.' } },
        { term: { sv: '+ Bild', en: '+ Image' },
          def:  { sv: 'Lägger till ett foto i inlägget via en bildlänk. Inlägg med foto får klart mer uppmärksamhet på Google.',
                  en: 'Adds a photo to the post via an image link. Posts with a photo get noticeably more attention on Google.' } },
        { term: { sv: '+ Knapp på inlägget', en: '+ Button on the post' },
          def:  { sv: 'Lägger till en klickbar knapp i inlägget, till exempel Boka eller Ring nu, och en länk dit knappen ska leda. Ge alltid läsaren nästa steg.',
                  en: 'Adds a clickable button to the post, such as Book or Call now, plus a link for the button to lead to. Always give the reader a next step.' } },
        { term: { sv: 'Schemalägg', en: 'Schedule' },
          def:  { sv: 'Låter dig välja datum och tid då inlägget ska publiceras automatiskt. Bra när du vill förbereda inlägg i förväg.',
                  en: 'Lets you pick a date and time when the post will be published automatically. Handy when you want to prepare posts in advance.' } },
        { term: { sv: 'Publicera på Google', en: 'Publish to Google' },
          def:  { sv: 'Knappen som lägger ut inlägget på din Google-profil. Har du valt ett datum schemaläggs det i stället.',
                  en: 'The button that puts the post on your Google profile. If you have picked a date, it is scheduled instead.' } },
        { term: { sv: 'Aktivt — X dagar kvar', en: 'Active — X days left' },
          def:  { sv: 'Inlägget syns fortfarande på din profil. Grönt betyder gott om tid, gult att det snart går ut, rött att det försvinner inom två veckor.',
                  en: 'The post is still visible on your profile. Green means plenty of time, yellow that it expires soon, red that it disappears within two weeks.' } },
        { term: { sv: 'Utgick för X dagar sedan', en: 'Expired X days ago' },
          def:  { sv: 'Inlägget har passerat sexmånadersgränsen och syns inte längre på Google. Dags att publicera något nytt.',
                  en: 'The post has passed the six-month limit and is no longer visible on Google. Time to publish something new.' } },
      ],
    },
    {
      id: 'photos',
      heading: { sv: 'Foton', en: 'Photos' },
      body: [
        {
          sv: 'Foton är det första kunder tittar på när de jämför företag på kartan. Profiler med bra och aktuella foton får fler samtal, fler vägbeskrivningar och fler klick till hemsidan. Fliken visar vilka foton du har, vilka som saknas och hur de presterar.',
          en: 'Photos are the first thing customers look at when comparing businesses on the map. Profiles with good, up-to-date photos get more calls, more direction requests and more clicks to the website. The tab shows which photos you have, which are missing and how they perform.',
        },
        {
          sv: 'Listan Foton att lägga till är din att-göra-lista. Google rekommenderar en uppsättning fototyper — omslagsfoto, logotyp, utsidan, insidan, teamet i arbete och exempel på dina arbeten. Etiketten på varje rad visar hur viktig fototypen är. Tryck Ladda upp så öppnas formuläret med rätt kategori förvald.',
          en: 'The Photos to add list is your to-do list. Google recommends a set of photo types — cover photo, logo, the outside, the inside, the team at work and examples of your work. The label on each row shows how important the photo type is. Press Upload and the form opens with the right category pre-selected.',
        },
        {
          sv: 'Under Dina foton ligger allt du laddat upp, sorterat efter visningar — översta raden är det som fungerar bäst. Klicka på ett foto för att se det i full storlek. Håll muspekaren över ett foto för att kunna ta bort det.',
          en: 'Under Your photos is everything you have uploaded, sorted by views — the top row is what works best. Click a photo to see it full size. Hover over a photo to be able to delete it.',
        },
        {
          sv: 'Kundfoton är bilder som kunder själva lagt upp på din profil. Du kan inte ta bort dem här — olämpliga foton anmäls direkt hos Google via länken längst ner.',
          en: 'Customer photos are pictures customers themselves have added to your profile. You cannot delete them here — inappropriate photos are reported directly to Google via the link at the bottom.',
        },
      ],
      terms: [
        { term: { sv: 'Foton att lägga till', en: 'Photos to add' },
          def:  { sv: 'Fototyperna som saknas på din profil. En komplett uppsättning gör att profilen sticker ut i sökresultat och på kartan.',
                  en: 'The photo types missing from your profile. A complete set makes the profile stand out in search results and on the map.' } },
        { term: { sv: 'Krävs / Rekommenderas starkt / Rekommenderas', en: 'Required / Strongly recommended / Recommended' },
          def:  { sv: 'Hur viktig fototypen är. Rött betyder att den behövs för en komplett profil — börja alltid med de röda.',
                  en: 'How important the photo type is. Red means it is needed for a complete profile — always start with the red ones.' } },
        { term: { sv: 'Antal foton', en: 'Number of photos' },
          def:  { sv: 'Hur många foton som ligger på din Google-profil just nu, dina egna och kundernas tillsammans.',
                  en: "How many photos are on your Google profile right now, your own and your customers' combined." } },
        { term: { sv: 'Fototyper som saknas', en: 'Missing photo types' },
          def:  { sv: 'Hur många av de rekommenderade fototyperna du inte laddat upp än. Målet är noll.',
                  en: 'How many of the recommended photo types you have not uploaded yet. The goal is zero.' } },
        { term: { sv: 'Senaste fotot', en: 'Latest photo' },
          def:  { sv: 'Antal dagar sedan du senast lade till ett foto. Google gillar aktiva profiler — sikta på minst ett nytt foto i månaden. Gult eller rött betyder att det var för länge sedan.',
                  en: 'Days since you last added a photo. Google likes active profiles — aim for at least one new photo a month. Yellow or red means it has been too long.' } },
        { term: { sv: 'Visningar', en: 'Views' },
          def:  { sv: 'Hur många gånger ett foto har visats för personer på Google. Foton med många visningar drar mest blickar — lägg upp fler i samma stil.',
                  en: 'How many times a photo has been shown to people on Google. Photos with many views draw the most eyes — add more in the same style.' } },
        { term: { sv: 'Omslagsfoto', en: 'Cover photo' },
          def:  { sv: 'Den stora bilden högst upp på din profil — det första kunder ser. Välj en tydlig, ljus bild som visar din verksamhet från sin bästa sida.',
                  en: 'The big image at the top of your profile — the first thing customers see. Pick a clear, bright image that shows your business at its best.' } },
        { term: { sv: 'Ladda upp foto', en: 'Upload photo' },
          def:  { sv: 'Öppnar formuläret där du väljer en bildfil och en kategori. Fotot skickas direkt till din Google-profil.',
                  en: 'Opens the form where you choose an image file and a category. The photo is sent straight to your Google profile.' } },
        { term: { sv: 'Kundfoton', en: 'Customer photos' },
          def:  { sv: 'Foton som kunder och andra Google-användare lagt till på din profil. Bra bilder är gratis marknadsföring — olämpliga anmäls hos Google.',
                  en: 'Photos that customers and other Google users have added to your profile. Good pictures are free marketing — inappropriate ones are reported to Google.' } },
      ],
    },
    {
      id: 'competitors',
      heading: { sv: 'Konkurrenter', en: 'Competitors' },
      body: [
        {
          sv: 'Din synlighet på Google är en tävling om samma kunder. Den här fliken visar hur du ligger till mot företagen omkring dig — vem kartan visar först, vem som samlar recensioner snabbast och hur era profiler skiljer sig. Allt uppdateras varje vecka.',
          en: 'Your visibility on Google is a race for the same customers. This tab shows how you compare with the businesses around you — who the map shows first, who is collecting reviews fastest and how your profiles differ. Everything updates every week.',
        },
        {
          sv: 'Raderna högst upp är veckans viktigaste händelser: till exempel att en konkurrent fått fler nya recensioner än du, eller att du klättrat en plats på kartan. Det är din snabba puls på läget.',
          en: "The rows at the top are the week's most important events: for example that a competitor got more new reviews than you, or that you climbed a spot on the map. It is your quick pulse on the situation.",
        },
        {
          sv: 'Recensionsracet visar vem som fått flest nya recensioner den här månaden. Den som samlar recensioner snabbast brukar klättra i kartresultaten. Ligger du efter är receptet enkelt: be varje nöjd kund om en recension — länken finns klar under fliken Recensioner.',
          en: 'The review race shows who has collected the most new reviews this month. Whoever collects reviews fastest tends to climb in the map results. If you are behind, the recipe is simple: ask every happy customer for a review — the link is ready under the Reviews tab.',
        },
        {
          sv: 'Tabellen längst ner jämför företagen på betyg, antal recensioner och foton. Använd den för att se var du halkar efter — och var du redan vinner.',
          en: 'The table at the bottom compares the businesses on rating, number of reviews and photos. Use it to see where you are falling behind — and where you are already winning.',
        },
      ],
      terms: [
        { term: { sv: 'Vilka Google visar först', en: 'Who Google shows first' },
          def:  { sv: 'De tre företag Google visar på kartan när någon gör din viktigaste sökning. Kallas ofta topp tre på kartan. Här klickar de flesta kunder — målet är att vara ett av de tre.',
                  en: 'The three businesses Google shows on the map when someone makes your most important search. Often called the top three on the map. This is where most customers click — the goal is to be one of the three.' } },
        { term: { sv: 'Recensionsracet denna månad', en: 'The review race this month' },
          def:  { sv: 'Antal nya recensioner varje företag samlat den här månaden. Din stapel är grön. Längst stapel leder racet.',
                  en: 'The number of new reviews each business has collected this month. Your bar is green. The longest bar leads the race.' } },
        { term: { sv: '↑ ökar / ↓ minskar / → samma', en: '↑ rising / ↓ falling / → same' },
          def:  { sv: 'Företagets takt jämfört med förra månaden. Ökar betyder att de samlar recensioner snabbare än förra månaden.',
                  en: "The business's pace compared with last month. Rising means they are collecting reviews faster than last month." } },
        { term: { sv: 'Avstånd', en: 'Distance' },
          def:  { sv: 'Hur långt bort företaget ligger från din adress. Ju närmare, desto mer tävlar ni om exakt samma kunder.',
                  en: 'How far the business is from your address. The closer it is, the more you compete for exactly the same customers.' } },
        { term: { sv: 'Betyg', en: 'Rating' },
          def:  { sv: 'Företagets genomsnittliga stjärnbetyg på Google. Gul siffra betyder att de ligger högre än du.',
                  en: "The business's average star rating on Google. A yellow number means they are rated higher than you." } },
        { term: { sv: 'Recensioner', en: 'Reviews' },
          def:  { sv: 'Företagets totala antal Google-recensioner sedan starten. Fler recensioner väger tungt i vem som visas först.',
                  en: "The business's total number of Google reviews since the start. More reviews weigh heavily in who shows up first." } },
        { term: { sv: 'Foton', en: 'Photos' },
          def:  { sv: 'Hur många foton företaget har på sin Google-profil. En fotorik profil drar fler blickar i sökresultaten.',
                  en: 'How many photos the business has on its Google profile. A photo-rich profile draws more eyes in the search results.' } },
        { term: { sv: 'På kartan / Topp 3', en: 'On the map / Top 3' },
          def:  { sv: 'Märket visar att företaget just nu ligger bland de tre första kartresultaten för din viktigaste sökning.',
                  en: 'The badge means the business is currently among the first three map results for your most important search.' } },
      ],
    },
    {
      id: 'audit',
      heading: { sv: 'Checklista', en: 'Checklist' },
      body: [
        {
          sv: 'Checklistan är en genomgång av din Google-profil, punkt för punkt. Varje bock gör profilen mer komplett — och kompletta profiler visas oftare och högre på Google. Siffran på fliken visar hur många punkter som återstår.',
          en: 'The checklist is a walkthrough of your Google profile, point by point. Every tick makes the profile more complete — and complete profiles show up more often and higher on Google. The number on the tab shows how many points remain.',
        },
        {
          sv: 'Punkterna är ordnade efter effekt. Störst effekt först: beskrivning, tjänster och foton påverkar mest hur ofta du visas och hur många som väljer dig. Sedan kommer företagsuppgifterna och sist den löpande aktiviteten.',
          en: 'The points are ordered by impact. Biggest impact first: the description, services and photos affect most how often you show up and how many people choose you. Then come the business details, and last the ongoing activity.',
        },
        {
          sv: 'Det mesta fixar du direkt härifrån. Tryck på knappen vid en punkt så öppnas ett litet formulär — det du skriver sparas direkt till din Google-profil. Håll muspekaren över en punkt för att se varför den spelar roll.',
          en: 'Most of it you can fix right here. Press the button next to a point and a small form opens — what you write is saved straight to your Google profile. Hover over a point to see why it matters.',
        },
        {
          sv: 'När allt är klart krymper listan till en månadsrutin: ett inlägg i månaden och ett jämnt flöde av recensioner. Det är det som håller dig före konkurrenter som satte upp sin profil en gång och sedan slutade.',
          en: 'Once everything is done, the list shrinks to a monthly routine: one post a month and a steady flow of reviews. That is what keeps you ahead of competitors who set up their profile once and then stopped.',
        },
      ],
      terms: [
        { term: { sv: 'X av 10 klara', en: 'X of 10 done' },
          def:  { sv: 'Hur många av checklistans punkter som är på plats. Stapeln är röd i början, gul en bit på väg och grön när allt är klart.',
                  en: 'How many of the checklist points are in place. The bar is red at the start, yellow part-way and green when everything is done.' } },
        { term: { sv: '✓ och ✗', en: '✓ and ✗' },
          def:  { sv: 'Grön bock betyder att punkten är klar. Rött kryss betyder att något saknas på din profil.',
                  en: 'A green tick means the point is done. A red cross means something is missing from your profile.' } },
        { term: { sv: 'Företagsbeskrivning', en: 'Business description' },
          def:  { sv: 'Texten som berättar vad du gör, var du finns och varför kunder ska välja dig. Hjälper Google att förstå ditt företag. Sikta på 250–750 tecken.',
                  en: 'The text that tells what you do, where you are and why customers should choose you. Helps Google understand your business. Aim for 250–750 characters.' } },
        { term: { sv: 'Tjänster listade', en: 'Services listed' },
          def:  { sv: 'Dina tjänster uppräknade på profilen. Gör att du visas även när folk söker på en specifik tjänst, inte bara ditt namn.',
                  en: 'Your services listed on the profile. Makes you show up even when people search for a specific service, not just your name.' } },
        { term: { sv: 'Omslagsfoto', en: 'Cover photo' },
          def:  { sv: 'Den första bilden kunder ser på din profil. En tydlig, professionell bild av ditt arbete eller din lokal.',
                  en: 'The first image customers see on your profile. A clear, professional picture of your work or your premises.' } },
        { term: { sv: 'Minst 3 egna foton', en: 'At least 3 of your own photos' },
          def:  { sv: 'Företag med fler foton får betydligt fler vägbeskrivningar och hemsideklick. Sikta på minst tio på sikt.',
                  en: 'Businesses with more photos get noticeably more direction requests and website clicks. Aim for at least ten over time.' } },
        { term: { sv: 'Telefonnummer', en: 'Phone number' },
          def:  { sv: 'Med numret på plats kan kunder ringa dig direkt från sökresultatet, utan att leta.',
                  en: 'With the number in place, customers can call you straight from the search result, without hunting.' } },
        { term: { sv: 'Hemsidelänk', en: 'Website link' },
          def:  { sv: 'Länken från profilen till din hemsida. Ger besökare och visar Google att företaget är etablerat.',
                  en: 'The link from the profile to your website. Brings visitors and shows Google the business is established.' } },
        { term: { sv: 'Öppettider', en: 'Opening hours' },
          def:  { sv: 'Visar kunder när de kan nå dig. Du syns dessutom i sökningar på "öppet nu".',
                  en: 'Shows customers when they can reach you. You also show up in "open now" searches.' } },
        { term: { sv: 'Egenskaper ifyllda', en: 'Attributes filled in' },
          def:  { sv: 'Detaljer som betalsätt, tillgänglighet och språk. De visas tydligt på profilen och hjälper rätt kunder att välja dig.',
                  en: 'Details like payment methods, accessibility and languages. They show clearly on the profile and help the right customers choose you.' } },
        { term: { sv: 'Inlägg de senaste 30 dagarna', en: 'A post in the last 30 days' },
          def:  { sv: 'Ett färskt inlägg visar Google och kunderna att företaget är aktivt. Ett i månaden räcker.',
                  en: 'A fresh post shows Google and customers that the business is active. One a month is enough.' } },
        { term: { sv: 'Minst 5 recensioner', en: 'At least 5 reviews' },
          def:  { sv: 'Profiler med fler recensioner visas högre och känns tryggare att välja. Be varje nöjd kund om en recension.',
                  en: 'Profiles with more reviews show up higher and feel safer to choose. Ask every happy customer for a review.' } },
        { term: { sv: 'Spara till Google', en: 'Save to Google' },
          def:  { sv: 'Knappen i formulären som skickar dina ändringar direkt till din Google-profil. Ändringen syns på Google kort därefter.',
                  en: 'The button in the forms that sends your changes straight to your Google profile. The change appears on Google shortly after.' } },
        { term: { sv: 'Månadsrutin', en: 'Monthly routine' },
          def:  { sv: 'De återkommande punkterna som blir kvar när profilen är komplett — inlägg och nya recensioner. Rutinen håller profilen levande.',
                  en: 'The recurring points that remain once the profile is complete — posts and new reviews. The routine keeps the profile alive.' } },
      ],
    },
  ],
}
