import { type SupportTopic } from '../types'

// Guide for the "Synlighet på Google" page. One section per visual block,
// in the order they appear on the page. Swedish only — the translation
// pass fills in English later.
export const synlighet: SupportTopic = {
  id:    'synlighet',
  title: { sv: 'Synlighet på Google', en: 'Visibility on Google' },
  intro: {
    sv: 'Den här sidan visar hur du syns när folk söker på Google. Du ser vilka sökningar du dyker upp för, hur högt du visas och var du går miste om besökare. Använd sidan för att välja vad du ska förbättra härnäst — inte för att kolla allt varje dag.',
    en: 'This page shows how you appear when people search on Google. You see which searches you show up for, how high you appear and where you are missing out on visitors. Use the page to choose what to improve next — not to check everything every day.',
  },
  sections: [
    {
      id: 'synlighet',
      heading: { sv: 'De tre korten högst upp', en: 'The three cards at the top' },
      body: [
        {
          sv: 'Korten sammanfattar din synlighet just nu. De svarar på tre frågor: hur många besökare får du från Google, hur många av dina sökord syns på första sidan, och var finns de enklaste förbättringarna.',
          en: 'The cards sum up your visibility right now. They answer three questions: how many visitors do you get from Google, how many of your keywords appear on page 1, and where are the easiest improvements.',
        },
        {
          sv: 'Två av korten går att klicka på. De hoppar direkt ner till rätt lista i sökordstabellen, så att du ser exakt vilka sökord som ligger bakom siffran.',
          en: 'Two of the cards are clickable. They jump straight down to the right list in the keyword table, so you can see exactly which keywords are behind the number.',
        },
        {
          sv: 'Uppe till höger byter du period — vecka, månad eller år. Hela sidan jämförs då mot föregående period. Titta på månad som standard; en enskild vecka svänger för mycket för att dra slutsatser av.',
          en: 'At the top right you switch period — week, month or year. The whole page then compares against the previous period. Look at month by default; a single week swings too much to draw conclusions from.',
        },
      ],
      terms: [
        { term: { sv: 'Klick denna månad', en: 'Clicks this month' },
          def:  { sv: 'Hur många gånger någon klickade sig vidare till din hemsida från ett sökresultat på Google. Pilen under visar förändringen mot förra perioden — grönt är uppåt, rött är nedåt.',
                  en: 'How many times someone clicked through to your website from a Google search result. The arrow below shows the change from the previous period — green is up, red is down.' } },
        { term: { sv: 'Sökord på sida 1', en: 'Keywords on page 1' },
          def:  { sv: 'Hur många av dina sökord som visas på Googles första resultatsida. Nästan ingen bläddrar längre än sida 1, så det är den här siffran ditt arbete ska höja.',
                  en: "How many of your keywords appear on Google's first results page. Hardly anyone goes past page 1, so this is the number your work should raise." } },
        { term: { sv: 'Snabba vinster', en: 'Quick wins' },
          def:  { sv: 'Sökord där du ligger på plats 4–15. De är närmast toppen och kräver minst arbete att lyfta. Börja alltid här när du har tid över.',
                  en: 'Keywords where you sit at position 4–15. They are closest to the top and take the least work to lift. Always start here when you have time to spare.' } },
        { term: { sv: 'Exempeldata', en: 'Sample data' },
          def:  { sv: 'Märket betyder att sidan visar påhittade siffror. Det försvinner när din Google-koppling är klar och riktig data börjat komma in.',
                  en: 'The badge means the page is showing made-up numbers. It disappears once your Google connection is done and real data has started coming in.' } },
      ],
    },
    {
      id: 'placeringar',
      heading: { sv: 'Vad som ändrats i dina placeringar', en: 'What changed in your rankings' },
      body: [
        {
          sv: 'Listan visar sökord som gått upp eller ner på Google sedan förra perioden. Det är sidans snabbaste sätt att se om ditt arbete ger resultat.',
          en: 'The list shows keywords that moved up or down on Google since the previous period. It is the fastest way on the page to see whether your work is paying off.',
        },
        {
          sv: 'Plats betyder var i sökresultaten du visas. Plats 1 är allra högst upp — en lägre siffra är alltså alltid bättre.',
          en: 'Position means where you appear in the search results. Position 1 is the very top — so a lower number is always better.',
        },
        {
          sv: 'Ett enstaka tapp är ingen kris; placeringar rör sig hela tiden. Men faller samma sökord flera perioder i rad bör du se över sidan det leder till och uppdatera innehållet.',
          en: 'A single drop is no crisis; rankings move all the time. But if the same keyword falls several periods in a row, review the page it leads to and update the content.',
        },
      ],
      terms: [
        { term: { sv: 'Pilen och färgen', en: 'The arrow and the colour' },
          def:  { sv: 'Grön pil uppåt betyder att sökordet klättrat. Röd pil nedåt betyder att det fallit. Texten under sökordet visar hur många platser.',
                  en: 'A green arrow up means the keyword climbed. A red arrow down means it fell. The text under the keyword shows how many positions.' } },
        { term: { sv: '#8 → #3', en: '#8 → #3' },
          def:  { sv: 'Var sökordet låg förra perioden och var det ligger nu. Siffran längst till höger är den aktuella platsen.',
                  en: 'Where the keyword sat last period and where it sits now. The number on the far right is the current position.' } },
        { term: { sv: 'Topp 3, Sida 1, Sida 2, Sida 3+', en: 'Top 3, Page 1, Page 2, Page 3+' },
          def:  { sv: 'Vilken resultatsida platsen motsvarar. Plats 1–10 är sida 1, plats 11–20 är sida 2, och därefter sida 3 eller längre bak.',
                  en: 'Which results page the position corresponds to. Positions 1–10 are page 1, positions 11–20 are page 2, and after that page 3 or further back.' } },
      ],
    },
    {
      id: 'trafik',
      heading: { sv: 'Trafikdiagrammen', en: 'The traffic charts' },
      body: [
        {
          sv: 'Två stapeldiagram visar din organiska trafik över tid — besökare från vanliga sökresultat, inte annonser. Visningar och klick hör ihop: först måste du synas, sedan måste någon välja dig.',
          en: 'Two bar charts show your organic traffic over time — visitors from regular search results, not ads. Impressions and clicks belong together: first you have to be seen, then someone has to choose you.',
        },
        {
          sv: 'Håll muspekaren över en stapel för exakta siffror och förändringen mot stapeln före. Det du vill se är en riktning uppåt över flera månader — inte en perfekt kurva.',
          en: 'Hover over a bar for exact numbers and the change from the bar before. What you want to see is an upward direction over several months — not a perfect curve.',
        },
        {
          sv: 'Många visningar men få klick betyder att du syns utan att locka. Då är det oftast sidtitlarna som behöver bli tydligare, inte placeringen.',
          en: 'Many impressions but few clicks means you are being seen without being chosen. Then it is usually the page titles that need to be clearer, not the ranking.',
        },
        {
          sv: 'Den gröna mätaren under diagrammen visar hur stor del av sökningarna som gällde din typ av tjänst, inte ditt företagsnamn. Den andelen är nya kunder — de som söker på ditt namn känner redan till dig.',
          en: 'The green meter under the charts shows what share of the searches were for your type of service, not your business name. That share is new customers — people who search your name already know you.',
        },
      ],
      terms: [
        { term: { sv: 'Visningar', en: 'Impressions' },
          def:  { sv: 'Hur många gånger din hemsida dök upp i sökresultaten, oavsett om någon klickade eller inte.',
                  en: 'How many times your website appeared in the search results, whether or not anyone clicked.' } },
        { term: { sv: 'Klick', en: 'Clicks' },
          def:  { sv: 'Hur många gånger någon klickade sig vidare till din hemsida från ett sökresultat.',
                  en: 'How many times someone clicked through to your website from a search result.' } },
        { term: { sv: 'Andel klick', en: 'Click rate (CTR)' },
          def:  { sv: 'Klick delat med visningar, i procent. Visar hur ofta de som ser dig faktiskt väljer dig.',
                  en: 'Clicks divided by impressions, as a percentage. Shows how often the people who see you actually choose you.' } },
        { term: { sv: 'Procenttalet vid mätaren', en: 'The percentage next to the meter' },
          def:  { sv: 'Andelen sökningar som gällde din tjänst i stället för ditt namn. Ju högre, desto fler helt nya kunder hittar dig via Google.',
                  en: 'The share of searches for your service rather than your name. The higher it is, the more completely new customers are finding you through Google.' } },
      ],
    },
    {
      id: 'sokord',
      heading: { sv: 'Dina sökord', en: 'Your keywords' },
      body: [
        {
          sv: 'Tabellen listar varje sökfras din hemsida visats för på Google. Flikarna ovanför filtrerar listan åt dig — siffran på varje flik visar hur många sökord som finns där.',
          en: 'The table lists every search phrase your website has appeared for on Google. The tabs above filter the list for you — the number on each tab shows how many keywords it holds.',
        },
        {
          sv: 'Klicka på en rad för en full genomgång av sökordet. Där ser du vad siffrorna betyder för just det ordet, hur mycket det kan ge, och konkreta steg för att förbättra det.',
          en: 'Click a row for a full walkthrough of the keyword. There you see what the numbers mean for that exact phrase, how much it could bring, and concrete steps to improve it.',
        },
        {
          sv: 'Jobba i den här ordningen: börja med Snabba vinster, ta sedan Setts men inte klickats. Behöver arbete kräver mest tid och kan vänta tills de andra är klara.',
          en: 'Work in this order: start with Quick wins, then take Seen but not clicked. Needs work takes the most time and can wait until the others are done.',
        },
      ],
      terms: [
        { term: { sv: 'Sökord', en: 'Keyword' },
          def:  { sv: 'Den exakta frasen någon skrev in på Google när din hemsida visades.',
                  en: 'The exact phrase someone typed into Google when your website appeared.' } },
        { term: { sv: 'Plats', en: 'Position' },
          def:  { sv: 'Var du rankar i resultaten — plats 1 är högst upp. Den lilla pilen visar månadens förändring, och texten under visar vilken resultatsida platsen motsvarar.',
                  en: "Where you rank in the results — position 1 is the very top. The small arrow shows this month's change, and the text underneath shows which results page the position corresponds to." } },
        { term: { sv: 'Klick', en: 'Clicks' },
          def:  { sv: 'Hur många som klickade sig till din hemsida från det här sökresultatet förra månaden.',
                  en: 'How many people clicked through to your website from this search result last month.' } },
        { term: { sv: 'Visningar', en: 'Times seen' },
          def:  { sv: 'Hur många gånger du visades i resultaten för frasen, oavsett om någon klickade.',
                  en: 'How many times you appeared in the results for the phrase, whether or not anyone clicked.' } },
        { term: { sv: 'Andel klick', en: 'Click rate' },
          def:  { sv: 'Hur stor del av dem som såg dig som klickade. Ett lågt tal på sida 1 tyder på en svag sidtitel eller beskrivning.',
                  en: 'The share of people who saw you who clicked. A low number on page 1 points to a weak page title or description.' } },
        { term: { sv: 'Topp 3 (etikett)', en: 'Top 3 (label)' },
          def:  { sv: 'Du ligger bland de tre översta resultaten — dit över hälften av alla klick går. Håll sidan uppdaterad och bevaka att platsen inte sjunker.',
                  en: 'You are among the top three results — where more than half of all clicks go. Keep the page updated and watch that the position does not slip.' } },
        { term: { sv: 'Snabb vinst (etikett)', en: 'Quick win (label)' },
          def:  { sv: 'Plats 4–15, strax utanför toppen. En liten förbättring av sidan kan ge många fler besökare — det bästa stället att lägga din tid.',
                  en: 'Position 4–15, just outside the top. A small improvement to the page can bring many more visitors — the best place to spend your time.' } },
        { term: { sv: 'Behöver arbete (etikett)', en: 'Needs work (label)' },
          def:  { sv: 'Plats 21 eller längre bak. Nästan ingen bläddrar så långt, så du syns utan att få besökare. Kräver nytt eller kraftigt förbättrat innehåll.',
                  en: 'Position 21 or further back. Hardly anyone browses that far, so you are seen without getting visitors. Requires new or heavily improved content.' } },
        { term: { sv: 'Får inga klick (etikett)', en: 'Not clicked (label)' },
          def:  { sv: 'Du syns på sida 1 men får klart färre klick än vad som är normalt för platsen. Vanligaste orsaken är en sidtitel som inte sticker ut i resultaten.',
                  en: 'You appear on page 1 but get far fewer clicks than is normal for the position. The most common cause is a page title that does not stand out in the results.' } },
        { term: { sv: 'Möjlig ökning om topp 3', en: 'Estimated gain if top 3' },
          def:  { sv: 'I detaljvyn: en uppskattning av hur många fler klick per månad sökordet kan ge om det når topp 3.',
                  en: 'In the detail view: an estimate of how many more clicks per month the keyword could bring if it reaches the top 3.' } },
        { term: { sv: 'Missade klick / månad', en: 'Missed clicks / month' },
          def:  { sv: 'I detaljvyn: ungefär hur många klick du går miste om varje månad jämfört med vad platsen normalt ger.',
                  en: 'In the detail view: roughly how many clicks you miss out on every month compared with what the position normally gives.' } },
      ],
    },
    {
      id: 'mojligheter',
      heading: { sv: 'Möjligheter', en: 'Opportunities' },
      body: [
        {
          sv: 'Här samlas sökord du inte rankar för ännu — men borde. Panelen har fyra flikar som svarar på var nästa kund kan komma ifrån.',
          en: 'This is where keywords you do not rank for yet — but should — are collected. The panel has four tabs that answer where the next customer could come from.',
        },
        {
          sv: 'Satsa på härnäst listar sökord värda att lägga till på din hemsida och Google-profil nu. Växande visar sökord där efterfrågan ökar jämfört med förra året — dit marknaden är på väg.',
          en: 'Target next lists keywords worth adding to your website and Google profile now. Growing shows keywords where demand is rising compared with last year — where the market is heading.',
        },
        {
          sv: 'Säsong visar kommande söktoppar för din bransch och när du behöver vara klar. Förbered innehållet innan toppen börjar — under själva toppen är det för sent.',
          en: 'Seasonal shows upcoming search peaks for your industry and when you need to be ready. Prepare the content before the peak starts — during the peak itself it is too late.',
        },
        {
          sv: 'Min bevakningslista låter dig följa valfria sökord månad för månad, även sådana du inte syns för alls. Lägg till ord du funderar på att satsa på och se om efterfrågan håller i sig.',
          en: 'My watchlist lets you follow any keywords month by month, even ones you are not visible for at all. Add words you are thinking about targeting and see whether the demand holds up.',
        },
      ],
      terms: [
        { term: { sv: 'Volym', en: 'Volume' },
          def:  { sv: 'Hur många som söker på frasen varje månad. Hög volym betyder fler möjliga besökare — men ofta också fler konkurrenter.',
                  en: 'How many people search the phrase each month. High volume means more potential visitors — but often more competitors too.' } },
        { term: { sv: 'Svårighet', en: 'Difficulty' },
          def:  { sv: 'Hur svårt det är att nå sida 1 för frasen. Låg svårighet i kombination med hyfsad volym är den bästa startpunkten.',
                  en: 'How hard it is to reach page 1 for the phrase. Low difficulty combined with decent volume is the best starting point.' } },
        { term: { sv: 'sök/mån', en: 'searches/mo' },
          def:  { sv: 'Genomsnittligt antal sökningar per månad det senaste året.',
                  en: 'The average number of searches per month over the last year.' } },
        { term: { sv: 'på 1 år', en: 'in 1 year' },
          def:  { sv: 'Hur mycket sökvolymen ändrats jämfört med samma period förra året. Plus betyder att efterfrågan växer, minus att den minskar.',
                  en: 'How much the search volume has changed compared with the same period last year. Plus means demand is growing, minus that it is shrinking.' } },
        { term: { sv: 'Lätt att ranka, Medel, Hård konkurrens', en: 'Easy to rank, Medium, Tough competition' },
          def:  { sv: 'Hur många andra som konkurrerar om frasen. Lätt att ranka betyder att en bra, vanlig sida ofta räcker för att synas.',
                  en: 'How many others compete for the phrase. Easy to rank means a solid, ordinary page is often enough to show up.' } },
        { term: { sv: 'Minidiagrammet', en: 'The mini chart' },
          def:  { sv: 'Sökvolymen månad för månad det senaste året. Grön linje pekar uppåt, röd pekar nedåt.',
                  en: 'The search volume month by month over the last year. A green line points up, a red one points down.' } },
        { term: { sv: 'Pågår nu / Börjar om X veckor', en: 'Ongoing now / Starts in X weeks' },
          def:  { sv: 'När sökningarna för säsongshändelsen börjar öka. Ditt innehåll ska ligga uppe innan dess.',
                  en: 'When searches for the seasonal event start to rise. Your content should be live before then.' } },
        { term: { sv: 'Topp', en: 'Peak' },
          def:  { sv: 'Perioden när sökningarna för händelsen är som flest.',
                  en: 'The period when searches for the event are at their highest.' } },
        { term: { sv: 'Du rankar redan för', en: 'You already rank for' },
          def:  { sv: 'Sökord kopplade till händelsen där du redan syns på Google, med din nuvarande plats.',
                  en: 'Keywords tied to the event where you are already visible on Google, with your current position.' } },
        { term: { sv: 'Sökord att förbereda för', en: 'Keywords to prepare for' },
          def:  { sv: 'Ord du ännu inte syns för. Skriv in dem på lämpliga sidor på hemsidan innan säsongen börjar.',
                  en: 'Words you are not visible for yet. Write them into suitable pages on your website before the season starts.' } },
        { term: { sv: 'Snittlinjen i stapeldiagrammet', en: 'The average line in the bar chart' },
          def:  { sv: 'Genomsnittet för de tolv månaderna i bevakningslistans diagram. Staplar över linjen är månader med högre efterfrågan än vanligt.',
                  en: "The average of the twelve months in the watchlist's chart. Bars above the line are months with higher demand than usual." } },
      ],
    },
    {
      id: 'sokkarta',
      heading: { sv: 'Lokal sökkarta', en: 'Local search map' },
      body: [
        {
          sv: 'Kartan visar var du syns i Google Maps-resultaten runt din adress. Rutan i mitten med vit ring är din adress, och varje ruta motsvarar ungefär en kvadratkilometer.',
          en: 'The map shows where you appear in the Google Maps results around your address. The square in the middle with the white ring is your address, and each square covers roughly one square kilometre.',
        },
        {
          sv: 'Placeringar på Maps är lokala. Du kan ligga etta nära din adress men vara osynlig två kilometer bort — kartan visar exakt var gränsen går.',
          en: 'Rankings on Maps are local. You can be number one near your address but invisible two kilometres away — the map shows exactly where the line goes.',
        },
        {
          sv: 'Byt sökord med knapparna ovanför kartan; varje ord har sin egen karta. Röda och tomma rutor i områden med många kunder är dina viktigaste förbättringsområden.',
          en: 'Switch keyword with the buttons above the map; each word has its own map. Red and empty squares in areas with many customers are your most important places to improve.',
        },
        {
          sv: 'Det som flyttar rutorna mot grönt är fler recensioner, en komplett Google-profil och att området nämns på din hemsida. Kartan uppdateras varje vecka, så du ser effekten av arbetet.',
          en: 'What moves the squares towards green is more reviews, a complete Google profile and mentioning the area on your website. The map updates every week, so you see the effect of the work.',
        },
      ],
      terms: [
        { term: { sv: 'Siffran i rutan', en: 'The number in the square' },
          def:  { sv: 'Din plats i Maps-resultaten just där. 1 betyder att du visas allra först.',
                  en: 'Your position in the Maps results right there. 1 means you show up first of all.' } },
        { term: { sv: 'Mörkgrön ruta (1–3)', en: 'Dark green square (1–3)' },
          def:  { sv: 'Du ligger i topp 3 i området — där de flesta klick och samtal hamnar.',
                  en: 'You are in the top 3 in that area — where most clicks and calls end up.' } },
        { term: { sv: 'Ljusgrön och gul ruta (4–10)', en: 'Light green and yellow square (4–10)' },
          def:  { sv: 'Du syns i listans första del men inte i toppen. Nära nog att lyfta med recensioner och en starkare profil.',
                  en: 'You appear in the first part of the list but not at the top. Close enough to lift with reviews and a stronger profile.' } },
        { term: { sv: 'Orange och röd ruta (11–20)', en: 'Orange and red square (11–20)' },
          def:  { sv: 'Du visas långt ner i resultaten. Få kunder hittar dig i det här området.',
                  en: 'You appear far down the results. Few customers find you in that area.' } },
        { term: { sv: 'Grå ruta med —', en: 'Grey square with —' },
          def:  { sv: 'Du finns inte bland de 20 första resultaten där. I praktiken är du osynlig i det området.',
                  en: 'You are not among the first 20 results there. In practice you are invisible in that area.' } },
        { term: { sv: 'Topp 3, Topp 10, Syns inte (korten)', en: 'Top 3, Top 10, Not visible (the cards)' },
          def:  { sv: 'Antal rutor av kartans 49 där du ligger i topp 3, i topp 10 respektive inte syns alls. Följ siffrorna vecka för vecka.',
                  en: "The number of the map's 49 squares where you are in the top 3, in the top 10, or not visible at all. Follow the numbers week by week." } },
      ],
    },
  ],
}
