import type { SiteContent } from '@/components/site/PreviewSite'
import { SERVICES } from '@/lib/services-data'

/*
 * The example site each trade opens with.
 *
 * It lives here, in a plain module, and not in PreviewSite — that file is a
 * client component, and a server page importing a plain object out of one
 * gets a stub back rather than the data. That is what emptied the template
 * demo's price list and what quietly dropped the trade defaults from every
 * published site whose owner had never edited a field.
 */

export const CONTENT: Record<string, SiteContent> = {
  salon: {
    businessName: 'Studio Söder',
    tagline:      'Din stund. Din stil.',
    kicker:       'Professionell hårvård',
    heroHeading:  'En upplevelse utöver det vanliga',
    heroBody:     'Vi kombinerar expertis med ett varmt välkomnande. Varje besök är skräddarsytt just för dig.',
    ctaText:      'Boka din tid',
    bookingUrl:   '',
    services: [
      { name: 'Klippning & styling', desc: 'Professionell klippning anpassad till ditt hår och din stil', price: 'från 650 kr' },
      { name: 'Färgning & slingor',  desc: 'Naturliga nyanser eller djärva förändringar',               price: 'från 1 200 kr' },
      { name: 'Behandlingar',        desc: 'Näring och vård som ger hälsosamt, starkt hår',             price: 'från 450 kr' },
    ],
    menuCategories: SERVICES.salon,
    aboutTitle: 'Vi sätter dig i fokus',
    aboutBody:  'Studio Söder grundades med en enkel vision: varje kund ska lämna med känslan av att ha blivit omhändertagen. Våra erfarna stylister lyssnar, rådger och levererar — varje gång.',
    navLinks:   ['Tjänster', 'Om oss', 'Kontakt'],
    phone:      '070 123 45 67',
    hours:      'Mån–Fre 09–19  ·  Lör 10–17',
    address:    'Södermalm, Stockholm',
  },
  spa: {
    businessName: 'Harmoni Spa',
    tagline:      'Ro för kropp och sinne.',
    kicker:       'Lyxig avkoppling',
    heroHeading:  'En fristad i vardagen',
    heroBody:     'Unna dig en stund av ren återhämtning. Välskötta händer, lugn atmosfär och behandlingar som gör verklig skillnad.',
    ctaText:      'Boka behandling',
    bookingUrl:   '',
    services: [
      { name: 'Klassisk massage',  desc: 'Avslappnande helkroppsmassage för minskad spänning',   price: '950 kr / 60 min' },
      { name: 'Ansiktsbehandling', desc: 'Djuprengöring och återfuktning för din hudtyp',         price: '1 050 kr / 60 min' },
      { name: 'Hotstone massage',  desc: 'Värme och tryck som löser upp spänningar på djupet',    price: '1 350 kr / 75 min' },
    ],
    menuCategories: SERVICES.spa,
    aboutTitle: 'En plats att andas',
    aboutBody:  'Harmoni Spa erbjuder en frizon mitt i stadens puls. Med noggrant utvalda behandlingsmetoder och en miljö skapad för ro hjälper vi dig att hitta din balans.',
    navLinks:   ['Behandlingar', 'Priser', 'Presentkort', 'Kontakt'],
    phone:      '08 123 45 67',
    hours:      'Mån–Sön 10–20',
    address:    'Östermalm, Stockholm',
  },
  restaurant: {
    businessName: 'Restaurang Örten',
    tagline:      'Smak som stannar kvar.',
    kicker:       'Välkommen till bordet',
    heroHeading:  'Mat lagad med passion och råvaror i säsong',
    heroBody:     'Vi väljer lokalt och lagar noggrant. Varje rätt är ett uttryck för det svenska köket.',
    ctaText:      'Boka bord',
    bookingUrl:   '',
    services: [
      { name: 'Lunch',          desc: 'Dagliga luncher med säsongsanpassade rätter',     price: '155 kr' },
      { name: 'À la carte',     desc: 'Kvällsmeny med noggrant curated vinkarta',         price: 'från 545 kr' },
      { name: 'Private dining', desc: 'Privat sällskap för fest, kick-off eller familj', price: 'Offert' },
    ],
    menuCategories: SERVICES.restaurant,
    aboutTitle: 'Hemlagat från grunden',
    aboutBody:  'Restaurang Örten startades 2018 av kocken Sara Lindqvist med ett löfte: inga genvägar. Varje rätt lagas från grunden med råvaror vi litar på.',
    navLinks:   ['Meny', 'Boka', 'Om oss', 'Kontakt'],
    phone:      '08 456 78 90',
    hours:      'Lunch Mån–Fre 11–14  ·  Middag Tis–Lör 17–22',
    address:    'Vasastan, Stockholm',
  },
  beauty: {
    businessName: 'Atelié Beauté',
    tagline:      'Skönhet utan kompromisser.',
    kicker:       'Professionell skönhetsvård',
    heroHeading:  'Behandlingar som lyfter ditt bästa jag',
    heroBody:     'Med precisionsarbete och premiumkvalitet levererar vi resultat du kan se — och känna.',
    ctaText:      'Boka tid',
    bookingUrl:   '',
    services: [
      { name: 'Fransförlängning',  desc: 'Individuell applikation för naturligt fylliga fransar', price: 'från 1 200 kr' },
      { name: 'Manikyr & pedikyr', desc: 'Nagelvård och lackering med hållbara produkter',        price: 'från 450 kr' },
      { name: 'Ögonbryn',          desc: 'Formning, färgning och styling för perfekta bågar',     price: 'från 350 kr' },
    ],
    menuCategories: SERVICES.beauty,
    aboutTitle: 'Precision i varje detalj',
    aboutBody:  'Vi grundade Atelié Beauté för att det saknades en plats där skönhetsvård verkligen togs på allvar. Resultaten talar för sig själva.',
    navLinks:   ['Behandlingar', 'Om oss', 'Boka'],
    phone:      '070 789 01 23',
    hours:      'Mån–Lör 09–18',
    address:    'Norrmalm, Stockholm',
  },
  fitness: {
    businessName: 'Pulse Träning',
    tagline:      'Starkare. Varje dag.',
    kicker:       'Gruppträning & personlig coaching',
    heroHeading:  'Nå din fulla potential',
    heroBody:     'Motiverande miljö, erfarna tränare och ett schema som passar dig. Oavsett nivå hittar du din plats hos oss.',
    ctaText:      'Kom igång',
    bookingUrl:   '',
    services: [
      { name: 'Gruppass 60 min',   desc: 'Energirika pass i grupp — alla nivåer välkomna',         price: '200 kr / pass' },
      { name: 'Personlig träning', desc: 'Individuellt anpassat program med din personliga coach', price: '850 kr / tillfälle' },
      { name: 'Kostrådgivning',    desc: 'Genomgång av kost och mål för bästa träningsresultat',   price: '750 kr / session' },
    ],
    menuCategories: SERVICES.fitness,
    aboutTitle: 'Gemenskap som driver dig',
    aboutBody:  'Pulse grundades med tron att träning är roligare och mer effektivt i grupp. Vi bygger ett sammanhang där du alltid välkomnas tillbaka — oavsett hur länge det gett sen sist.',
    navLinks:   ['Schema', 'Träning', 'Om oss', 'Kontakt'],
    phone:      '070 234 56 78',
    hours:      'Mån–Fre 06–21  ·  Lör–Sön 08–18',
    address:    'Kungsholmen, Stockholm',
  },
  cleaning: {
    businessName: 'Städproffs AB',
    tagline:      'Rent hem. Fri tid.',
    kicker:       'Professionell städservice',
    heroHeading:  'Vi städar så att du kan leva',
    heroBody:     'Bakgrundskontrollerade städare, eco-certifierade produkter och alltid punktliga. Boka enkelt online — kom hem till ett skinande rent hem.',
    ctaText:      'Begär offert',
    bookingUrl:   '',
    services: [
      { name: 'Hemstädning',        desc: 'Regelbunden städning av hela bostaden — badrum, kök och alla rum', price: 'från 1 195 kr' },
      { name: 'Storstädning',       desc: 'Grundlig städning inkl. ugn, kyl, fönster och garderober',         price: 'från 2 995 kr' },
      { name: 'Kontorsstäd',        desc: 'Löpande städning av kontor och gemensamma lokaler',                price: 'Offert' },
    ],
    menuCategories: SERVICES.cleaning,
    aboutTitle: 'Rent hem — varje gång',
    aboutBody:  'Städproffs grundades med ett enkelt löfte: att leverera det vi lovar, varje gång. Alla våra städare är bakgrundskontrollerade, utbildade och delar vår stolthet i ett välgjort jobb.',
    navLinks:   ['Tjänster', 'Priser', 'Om oss', 'Kontakt'],
    phone:      '08 123 45 67',
    hours:      'Mån–Fre 07–18  ·  Lör 08–14',
    address:    'Stockholm & Stockholms län',
  },
  craftsman: {
    businessName: 'Hantverk & Bygg AB',
    tagline:      'Jobbet gjort — på riktigt.',
    kicker:       'Bygg & hantverksarbeten',
    heroHeading:  'Vi bygger det du drömmer om',
    heroBody:     'Gedigen erfarenhet, egna hantverkare och ett löfte om att alltid leverera kvalitet. Från offert till färdigt projekt.',
    ctaText:      'Begär offert',
    bookingUrl:   '',
    services: [
      { name: 'Snickeriarbete',           desc: 'Anpassade lösningar i trä — kök, inredning, uteplatser', price: 'från 950 kr/h' },
      { name: 'Målning & puts',           desc: 'Invändigt och utvändigt målningsarbete av hög standard',  price: 'från 650 kr/h' },
      { name: 'Montering & installation', desc: 'Möbler, kök, badrum och allt däremellan',                price: 'från 550 kr/h' },
    ],
    menuCategories: SERVICES.craftsman,
    aboutTitle: '30 år av hantverk',
    aboutBody:  'Hantverk & Bygg AB startades 1994 av grundaren Per Karlsson med ett enkelt löfte: vi gör det vi säger vi ska göra. Idag är vi 12 hantverkare som delar samma stolthet.',
    navLinks:   ['Tjänster', 'Projekt', 'Om oss', 'Kontakt'],
    phone:      '070 567 89 01',
    hours:      'Mån–Fre 07–16',
    address:    'Stockholm',
  },
  other: {
    businessName: 'Din Verksamhet',
    tagline:      'Välkommen.',
    kicker:       'Professionell service',
    heroHeading:  'Vi är här för att hjälpa dig',
    heroBody:     'Erfarenhet, engagemang och kvalitet i allt vi gör. Kontakta oss för att komma igång.',
    ctaText:      'Kontakta oss',
    bookingUrl:   '',
    services: [
      { name: 'Tjänst ett', desc: 'Beskrivning av vad tjänsten innebär för kunden', price: 'Offert' },
      { name: 'Tjänst två', desc: 'Beskrivning av vad tjänsten innebär för kunden', price: 'Offert' },
      { name: 'Tjänst tre', desc: 'Beskrivning av vad tjänsten innebär för kunden', price: 'Offert' },
    ],
    menuCategories: SERVICES.other,
    aboutTitle: 'Om oss',
    aboutBody:  'Vi grundades med ett tydligt syfte och jobbar varje dag för att uppfylla det. Välkommen att ta kontakt.',
    navLinks:   ['Tjänster', 'Om oss', 'Kontakt'],
    phone:      '070 000 00 00',
    hours:      'Mån–Fre 09–17',
    address:    'Sverige',
  },
}
